# Generated by Django 4.1.7 on 2023-06-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_problems_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='problems',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
