# Generated by Django 4.1.7 on 2023-06-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alert_image_problems_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='problem',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='account.problems'),
        ),
    ]
