# Generated by Django 4.1.7 on 2023-06-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_alert_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='problem',
        ),
    ]
